// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCsPjDyHcGejXuQul5FeIIQNtFHFGAa98s',
    appId: '1:358389882247:web:eef6c64bcc1af8625c0722',
    messagingSenderId: '358389882247',
    projectId: 'only-write',
    authDomain: 'only-write.firebaseapp.com',
    storageBucket: 'only-write.firebasestorage.app',
    measurementId: 'G-3S17VJT7EB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC-VPBsUJYdG4EnArjJLdmWjpdnjCNm0Wo',
    appId: '1:358389882247:android:d1885104c8248f745c0722',
    messagingSenderId: '358389882247',
    projectId: 'only-write',
    storageBucket: 'only-write.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAPA4Km5BSfvLsv2JA0WaKfsIX0LqquQrw',
    appId: '1:358389882247:ios:9ae318193a7161825c0722',
    messagingSenderId: '358389882247',
    projectId: 'only-write',
    storageBucket: 'only-write.firebasestorage.app',
    iosBundleId: 'com.example.writeOnly',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAPA4Km5BSfvLsv2JA0WaKfsIX0LqquQrw',
    appId: '1:358389882247:ios:9ae318193a7161825c0722',
    messagingSenderId: '358389882247',
    projectId: 'only-write',
    storageBucket: 'only-write.firebasestorage.app',
    iosBundleId: 'com.example.writeOnly',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCsPjDyHcGejXuQul5FeIIQNtFHFGAa98s',
    appId: '1:358389882247:web:f0c224e3a14582ee5c0722',
    messagingSenderId: '358389882247',
    projectId: 'only-write',
    authDomain: 'only-write.firebaseapp.com',
    storageBucket: 'only-write.firebasestorage.app',
    measurementId: 'G-JR8GMQSW66',
  );
}
